version: '3.8'

services:
  app:
    build: .
    ports:
      - "3000:3000"  # Exemplo de porta que sua aplicação Node pode usar
    volumes:
      - .:/home/node/app

  db:
    image: mysql:8.0
    container_name: mysql_db
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: nest
